
app: payment-management
service: payment-management

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

provider:
  name: aws
  runtime: python3.8

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
